{% set version = '0.9.11' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-batchtools
  version: {{ version|replace("-", "_") }}

source:
  fn: batchtools_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/batchtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/batchtools/batchtools_{{ version }}.tar.gz
  sha256: 1b64166c944ed7693abe1496421b8cdb338097b9c338a98e76654b767d10b20a

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-backports >=1.1.2
    - r-base64url >=1.1
    - r-brew
    - r-checkmate >=1.8.5
    - r-data.table >=1.11.2
    - r-digest >=0.6.9
    - r-fs >=1.2.0
    - r-progress >=1.1.1
    - r-rappdirs
    - r-stringi
    - r-withr >=2.0.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-r6
    - r-backports >=1.1.2
    - r-base64url >=1.1
    - r-brew
    - r-checkmate >=1.8.5
    - r-data.table >=1.11.2
    - r-digest >=0.6.9
    - r-fs >=1.2.0
    - r-progress >=1.1.1
    - r-rappdirs
    - r-stringi
    - r-withr >=2.0.0

test:
  commands:
    - $R -e "library('batchtools')"           # [not win]
    - "\"%R%\" -e \"library('batchtools')\""  # [win]

about:
  home: https://github.com/mllg/batchtools
  license: LGPL-3
  summary: As a successor of the packages 'BatchJobs' and 'BatchExperiments', this package provides
    a parallel implementation of the Map function for high performance computing systems
    managed by schedulers 'IBM Spectrum LSF' (<https://www.ibm.com/us-en/marketplace/hpc-workload-management>),
    'OpenLava' (<http://www.openlava.org/>), 'Univa Grid Engine'/'Oracle Grid Engine'
    (<http://www.univa.com/>), 'Slurm' (<http://slurm.schedmd.com/>), 'TORQUE/PBS' (<http://www.adaptivecomputing.com/products/open-source/torque/>),
    or 'Docker Swarm' (<https://docs.docker.com/swarm/>). A multicore and socket mode
    allow the parallelization on a local machines, and multiple machines can be hooked
    up via SSH to create a makeshift cluster. Moreover, the package provides an abstraction
    mechanism to define large-scale computer experiments in a well-organized and reproducible
    way.
  license_family: LGPL

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - nick-youngblut
