travis:
  secure:
    BINSTAR_TOKEN: BhsVFqpgboAOw04KY4vEZBqeZbsY7GC1i1z4qIPeIcQaZzPOQBjoneBVHaco1DaIMbXOoRCbr5Z4evW/KWjR1VaRmJ2WzA+jCv9Z4Jkx5WL+Ip4+BMLc+qYEE9uV6OXRpa84KspTM9shVpCkoV5qH61oJ0ZwLLF6I9aq8CfInfOa4rQ+sSX2w126shN3i4EENuwdgy3NvZv32zO5REGBFxZY7PNitMLsOvnjKIj6BReHhbJM1LCDUG128XezKTbTX19ZgWu+b3CNS9WYnNhVyZjoEkyWiOgncXA+OtfguXcunZS2kEmrbMljmNE6s5ypEqQZaO5Qn1cB8CRW1n4I98Bes4Wqwj+hDbn5UIlxR4DY4aADEZj97o8DWomY7yzLdqO0dV1bXEUHdTNpZWoKtifmzjobWyscEw58DYwfDc1+mp/r16I8RRdcwfGA2UXkGXwdMEETGvA9cwFZ42LY4F4PAfgf7SWQ/1rbhC8zIGTD6o8sRhb82tiaMAwix7m80PBSuXpG1dHDJCpbx9QrK4NDX0axJSvM2AfEg5AzRj84zyFKWwMyYY+OVq5v8aYGTeIJxnwJzaBwskDpGW7u43VQMBZFa3VGC+z8k8mygfM5UoK5ul553jmE2NubZ9OYEgjmhfzQErh8LAHcrCeNelmxbs3H/zGiIhuttTCVB0M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
